
spring.application.name=StockPrice
alphaVantage.API.KEY = YPVOPCO6V4KA9WJ3
alphaVantage.url = https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol=%s&apikey=%s
spring.security.enabled=false